#+TITLE: Monster Trading Card Game
:FILE-OPTIONS:
#+STARTUP: fold
#+OPTIONS: toc:nil
#+OPTIONS: num:2
#+OPTIONS: \n:t
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \renewcommand{\familydefault}{\sfdefault}
#+LATEX_HEADER: \usepackage{nopageno}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \usepackage[a4paper, margin=2.5cm]{geometry}
:END:

* Intro
This is a RESTful trading card game written in Java. The assignment description,
OpenAPI specification, and general documentation for the project can be found in
the [[file:documentation/][documentation]] folder. All documentation and project organization was written
and accomplished using [[https://orgmode.org/][org-mode]]. Markdown and pdf versions of the documentation
are also included.

* Building
The project =Makefile= can be used to build and test the project. Included
integration tests in the form of shell scripts may need to be set as executable
before they can be run.

* Class Diagrams
Class diagrams in the form of a PlantUML file are generated during the build
process. You may compile and view them with the =Makefile= as well, though this
requires the =plantuml= executable. On platforms other than GNU/Linux you will
probably need to manually open the generated class diagram image with your
favorite image viewer. It will be output to =target/generated-docs/mtcg.png=

