# Use postgres/example user/password credentials
version: '3.1'

services:
  mtcg-db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: mtcg-user
      POSTGRES_PASSWORD: mtcg-pass
      POSTGRES_DB: mtcg-db
    volumes:
      - mtcg-db:/var/lib/postgresql/data
  adminer_custom:
    build: .
    restart: always
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - 8080:8080

volumes:
  mtcg-db:
    driver: local
