# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: swen1pw

  adminer:
    image: adminer:4.8.1
    restart: always
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - 8080:8080
