@startuml

class Server {
       - ArrayList<User> activeUsers
}

class User {
        - ArrayList<Card> stack
        - ArrayList<Card> deck
        - Credentials credentials
        - int coins

        + void manageCards()
        + void tradeCards()
        + void buyCardPack()
        + ArrayList<Card> getStack()
        + ArrayList<Card> getDeck()

        - void addCardToDeck()
        - void updateStack(ArrayList<Card> pack)
}

abstract class Card {
        - final int damage

        + int getDamage()
}

class Credentials {
        - String username
        - String password

        + String getUsername()
        + String getPassword()
}

User .. Card
User .. Credentials
User .. Server

enum MonsterType {
        DRAGON
        GOBLIN
        KNIGHT
        ELF
}
enum Element {
        WATER
        EARTH
        FIRE
}

class MonsterCard {
        - Element element
        - MonsterType type

        + Element getElement()
        + MonsterType getType()
}
class SpellCard {
        - Element element

        + Element getElement()
}

Card <|- MonsterCard
Card <|- SpellCard

MonsterCard .. MonsterType
MonsterCard .. Element

SpellCard .. Element

@enduml
